// Project Euler: Problem 2: Even Fibonacci Numbers (freecodecamp)
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence that do not exceed the nth term, 
// find the sum of the even-valued terms.

function fiboEvenSum(n) {
    let num1 = 1;
    let num2 = 2;
    let sum = 0;
    const fibArr = [1, 2];
    for (let i = 0; i < n - 2; i++) {
        let num3 = num1 + num2;
        fibArr.push(num3);
        num1 = num2;
        num2 = num3;
    };
    for (let i = 0; i < fibArr.length; i++) {
        if (fibArr[i] % 2 === 0) {
            sum += fibArr[i];
        }
    };
    return sum;
};

console.log(fiboEvenSum(10));